kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: 2048-game-app
  namespace: traefik
spec:
  routes:
    - kind: Rule
      match: PathPrefix(`/2048`)
      services:
        - name: svc-2048
          namespace: game2048
          port: 8000
